version: '3.8'

services:
  nginx:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api/dev.db/:/usr/src/app/dev.db

