version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: web-ui/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api/dev.db:/usr/src/app/api/dev.db
