services:
  nginx:
    build:
      context: .
      dockerfile: web-ui/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        POSTGRES_DB: mydatabase
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: mypassword
        POSTGRES_HOST: postgres
        DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase
    ports:
      - "3000:3000"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST: postgres
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase
    depends_on:
      - postgres

volumes:
  postgres_data:
