name: CI/CD web-ui

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: geoffolson/ABQuest
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - run: npm run test --workspace=web-ui
      - run: npm run lint --workspace=web-ui
